const BASE58_ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
const PROGRAM_ID = 'oreV3EG1i9BEgiAJ8b177Z2S2rMarzak4NMv1kULvWv';
const ENTROPY_PROGRAM_ID = '3jSkUuYBoJzQPMEzTvkDFXCZUBksPamrVhrnHR9igu2X';
const VAR_ADDRESS = 'BWCaDY96Xe4WkFq1M7UiCCRcChsJ3p51L5KrGzhxgm2E';
const LAMPORTS_PER_SOL = 1_000_000_000;
const ORE_MINT_ADDRESS = 'oreoU2P8bN6jkk3jbaiVxYnG1dCXcYxwhwyK9jSybcp';
const MAX_CONSECUTIVE_ERRORS = 5;
const MOTHERLODE_CACHE_TTL = 30000;
const STORAGE_KEYS = {
    SETTINGS: 'ore_bot_settings',
    STATS: 'ore_bot_stats',
    HISTORY: 'ore_bot_history'
};
const DEPLOY_DISCRIMINATOR = 6;
const CLAIM_SOL_DISCRIMINATOR = 3;
const CHECKPOINT_DISCRIMINATOR = 2;

